### ISSUE TITLE
db wilayah = db rajaongkir?

### ISSUE THREAD

**Issue by Not-Invalid** [cahyadsn/db_rajaongkir#1]
permisi mas saya sebelumya memakai api data wilayah punya mas cahya di project sekolah saya, dan di project ini ada integrasi sama API raja ongkir. saya mau tanya apakah kalo saya pakai db wilayah bisa diintegrasiin ke raja ongkir nya?

**Comment by cahyadsn** [comment]
Kode yg dipakai di raja ongkir berbeda dengan kode wilayah administrasi pemerintahan yg ada di repo 'wilayah'. Kode di raja ongkir bersifat internal, hanya berlaku untuk digunakan di API raja ongkir saja

**Comment by aacassandra** [comment]
ini db nya sudah beda ya mas dengan data rajaongkir terbaru, ada datanya ga mas?
